### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by 314eter** [tree-sitter/tree-sitter-ocaml#11]
@maxbrunsfeld Can you do a new release? I have a PR ready for [language-ocaml](https://github.com/toroidal-code/language-ocaml), which depends on tree-sitter-ocaml.

**Comment by maxbrunsfeld** [comment]
Ok, version 0.12.1 is published. I've made some changes to address the compile speed, which would be a problem for users installing an Atom package. It now compiles from scratch in about 37 seconds on my macbook pro, which is still slow, but not a showstopper.

**Comment by 314eter** [comment]
Nice. I think the version of `tree-sitter-cli` in the dependencies should be at least `0.12.6` to support the word property.
