### ISSUE TITLE
Hangs on invalid strings

### ISSUE THREAD

**Issue by Kerl13** [tree-sitter/tree-sitter-ocaml#26]
When parsing the example code given below, tree-sitter-ocaml hangs forever and incurs a very high CPU usage and memory consumption.

```
===========
Invalid strings
===========
let _ = "\"
---
(compilation_unit
 (value_definition
  (let_binding
   (value_name)
   (string (escape_sequence) (MISSING)))))
```

This can be annoying since it happens every time one wants to write `\n` at the end of a string in Atom

**Comment by 314eter** [comment]
This was caused by my attempt to allow null characters in strings, and is fixed in #27.
