### ISSUE TITLE
build-wasm: generated .wasm file excessively large and not working

### ISSUE THREAD

**Issue by cancerberoSgx** [tree-sitter/tree-sitter-ocaml#30]
Repro steps: 
```
npm i tree-sitter-ocaml
npx tree-sitter build-wasm node_modules/tree-sitter-ocaml
```
This will generate tree-sitter-ocaml.wasm , with 19MB size and it will throw the following error while executing with node.js: 

```
 message: 'Cannot read property \'apply\' of undefined',
 node_modules/web-tree-sitter/tree-sitter.js:1
  t.startsWith.e.(anonymous function) (node_modules/web-tree-sitter/tree-sitter.js:1:7182)
  Object.Module._ts_parser_parse_wasm (node_modules/web-tree-sitter/tree-sitter.js:1:37989)
  Parser.parse (node_modules/web-tree-sitter/tree-sitter.js:1:47548)
```

Ii think there's something wrong with it, since the rest of the grammars generates .wasm of no more that 1-2 MB.

**Comment by cancerberoSgx** [comment]
Update: updating dependencies generates a 6MB file but still fails to execute with the same error. Probably is combining some low level dependencies ?

**Comment by 314eter** [comment]
I didn't get exactly the same error message, but #31 fixed it for me. The size is still 6MB, but the performance is good.

**Comment by maxbrunsfeld** [comment]
Thanks for these reports on the wasm code size, and sorry that it can still be a bit large in some cases. Things got better in Tree-sitter 0.15.3, https://github.com/tree-sitter/tree-sitter/pull/334 will make them a bit better still, and there's still more work to do on code size.
