### ISSUE TITLE
conversion_specification are not recognzed within quoted strings

### ISSUE THREAD

**Issue by undu** [tree-sitter/tree-sitter-ocaml#47]
Quoted string don't contain escape sequences, but they can contain conversion specifications, they should be added. For validation purposes an example should be added to https://github.com/tree-sitter/tree-sitter-ocaml/blob/master/ocaml/corpus/expressions.txt

**Comment by 314eter** [comment]
That would indeed be nice, but I'm not sure it's possible. Quoted strings are parsed by an external scanner because there is no other way to check that the opening and closing id's match. But external scanners can only return terminal symbols, so they can't contain anything else.

**Comment by maxbrunsfeld** [comment]
In Ruby, the external scanner parses strings' start and end delimiters as separate tokens, and in between it stores the delimiters as state. If we wanted to, we could do the same thing here. I'm not sure if it's worth the complexity, but possible.
