### ISSUE TITLE
Circular Dependency with "_expression", "_simple_expression", and "infix_expression"

### ISSUE THREAD

**Issue by berchn** [tree-sitter/tree-sitter-ocaml#52]
I'm generating classes from `ocaml/src/node_types.json`, and I'm running into a circular dependency issue between "_expression", "_simple_expression", and "infix_expression". "infix_expression" appears in the subtypes of both "_expression" and "_simple_expression"'. The following is modified error output from my compiler:

```
While computing the class precedence list of the class named infix_expression.
It is not possible to compute the class precedence list because
there is a circularity in the local precedence relations.

This arises because:
  The class named                    _expression
    follows the class named          _argument
    in the supers of the class named _simple_expression.

  The class named                    _simple_expression
    follows the class named          _expression
    in the supers of the class named infix_expression.

  The class named                            _argument
    appears in the supers of the class named _simple_expression.
```

**Comment by maxbrunsfeld** [comment]
That's interesting. It seems like a bug in Tree-sitter's generation of those `node-types` entries. FWIW, the relevant code for that is here: https://github.com/tree-sitter/tree-sitter/blob/335190cc1d95baa7f9b50c4c4dee86173c46cc0a/cli/src/generate/node_types.rs#L558-L575.

**Comment by 314eter** [comment]
It's not a bug in tree-sitter, it's because I aliased `hash_expression` to `infix_expression`:

```javascript
_simple_expression: $ => choice(
  ...
  alias($.hash_expression, $.infix_expression),
  ...
),

_expression: $ => choice(
  ...
  $.infix_expression,
  ...
)
```

I did that because operators that start with a hash sign are infix operators, but they have slightly different precedence rules. We can remove the alias to fix it.

@berchn Is this the only circular dependency?

**Comment by berchn** [comment]
No, if I remove the alias for `hash_expression`, I also have an issue with `prefix_expression`.
