### ISSUE TITLE
Bump to version 20 of tree-sitter

### ISSUE THREAD

**Issue by VixieTSQ** [tree-sitter/tree-sitter-ocaml#57]
I tried to do this myself but this repo is different most tree-sitter repos as it really has 2 parsers. I couldn't figure out how exactly this should work in the bindings.

**Comment by 314eter** [comment]
I updated tree-sitter and did a rebuild.

@maxbrunsfeld Can you release a new version on NPM and crates.io?

**Comment by VixieTSQ** [comment]
> I updated tree-sitter and did a rebuild.

@314eter The rust binding still depends on tree-sitter 0.19 in cargo.toml.

**Comment by 314eter** [comment]
Fixed in #58.

**Comment by torhovland** [comment]
This still needs a release.

**Comment by 314eter** [comment]
@maxbrunsfeld Can you create a new release?

**Comment by aryx** [comment]
I've created a new release: https://github.com/tree-sitter/tree-sitter-ocaml/releases/tag/v0.20.0

**Comment by aryx** [comment]
Can we close the issue?

**Comment by 314eter** [comment]
@aryx I created a new release with the latest changes. Do you have access to the tree-sitter organization on crates.io and NPM to publish the new version there? I can only create releases on Github.

**Comment by aryx** [comment]
I think we could add an action like they did for tree-sitter-java.
See this thread: https://github.com/tree-sitter/tree-sitter-java/pull/98

**Comment by 314eter** [comment]
That looks like a good solution for crates.io. It would be nice to have something similar for NPM. I see https://www.npmjs.com/package/tree-sitter-java is still on 0.19.1 too.

**Comment by VixieTSQ** [comment]
Should this issue still be open? It looks like the issue is, is that the new changes weren't pushed to crates.io? Am I correct in that?

**Comment by 314eter** [comment]
I'll close this one and create a new issue to implement the publish action.
