### ISSUE TITLE
`let` operators don't allow a value name

### ISSUE THREAD

**Issue by kopecs** [tree-sitter/tree-sitter-ocaml#59]
It seems like value-names are not supported for `let` operator bindings, e.g.,

```ocaml
let ( let* ) = Option.bind in
let xs = Some 5 in
let* xs in
Some (xs + 3)
```

but this should be permitted per the production for `letop-binding` in the OCaml language extensions documentation

```
letop-binding ::= pattern = expr
                | value-name
```
<https://v2.ocaml.org/manual/bindingops.html>

**Comment by 314eter** [comment]
Let punning support was added in #50, but there hasn't been a new release since then.

**Comment by kopecs** [comment]
Ah, missed that. Thanks!
