### ISSUE TITLE
Parsing errors in .mli files

### ISSUE THREAD

**Issue by jinh0** [tree-sitter/tree-sitter-ocaml#60]
Example:

<img width="1272" alt="Screen Shot 2022-09-05 at 12 05 52 AM" src="https://user-images.githubusercontent.com/40512164/188358578-21bc0b3a-8f2a-4c92-a19e-28d188ccb7c4.png">

**Comment by 314eter** [comment]
You're using the `ocaml` instead of `ocaml_interface` grammar for a `.mli` file. Which editor are you using?
