### ISSUE TITLE
( <|> ) does not play well with highlighting

### ISSUE THREAD

**Issue by lthms** [tree-sitter/tree-sitter-ocaml#72]
Inserting the following line in a `mli` file

```
val ( <|> ) : 'a -> 'a -> 'a
```

(or any other type, really, the culprit is `<|>` as far as I can tell)

will see the highlighting of the tree sitter to go wild, in particular for the docstrings.

See with and without TS highlighting enabled in Neovim.

![2023-04-24-21:53:06](https://user-images.githubusercontent.com/1141231/234102180-a5d4ed8d-0027-46a5-aaba-6fff445852d9.png)
![2023-04-24-21:53:28](https://user-images.githubusercontent.com/1141231/234102197-e7333c24-b0d3-42c2-b588-cf8843c16626.png)

I don’t think it is coming from my setup.

Happy to help resolving this issue. I will try to scheme the codebase to see where the issue could come from, and any pointer is welcome.

Thanks for the project in any case!

**Comment by 314eter** [comment]
This is how `tree-sitter highlight` highlights it:
![highlight](https://user-images.githubusercontent.com/890465/234138055-3f6db947-965a-499a-b527-869444b5f8cd.png)
So I don't think tree-sitter or tree-sitter-ocaml are the problem.

**Comment by lthms** [comment]
My bad :sweat_smile: thanks for letting me know!
