### ISSUE TITLE
Multi-line strings are not highlighted correctly

### ISSUE THREAD

**Issue by Innf107** [tree-sitter/tree-sitter-ocaml#74]
Multiline strings like the following are valid OCaml but are highlighted as if they were code.

```ocaml
let str = {|
something let something else
|}
```

**Comment by 314eter** [comment]
Which tool/editor are you using?

**Comment by Innf107** [comment]
Ah sorry, this was prompted by the syntax highlighting here on github, but I should have probably guessed that their version is out of date. If I manually run `tree-sitter highlight`, everything is highlighted correctly.

Do you know where I could open an issue (if at all) to get them to update their version of this grammar?

**Comment by 314eter** [comment]
GitHub is not using tree-sitter for OCaml highlighting. They're using https://github.com/textmate/ocaml.tmbundle, which is a really outdated TextMate grammar that breaks in a lot of cases.

They're only using tree-sitter for a [limited list](https://github.com/github-linguist/linguist/blob/master/script/list-grammars#L8-L25) of languages. The result with tree-sitter-ocaml would be a lot better, but that's an internal decision. Maybe it can help to ask on https://support.github.com/contact.
