### ISSUE TITLE
Allow standalone type expressions

### ISSUE THREAD

**Issue by mizlan** [tree-sitter/tree-sitter-ocaml#84]
Would it be controversial to add support for parsing a source file as just a type expression? E.g., `'a -> int -> 'b`.

Motivation: The OCaml LSP server returns markdown upon `textDocument/hover`, and Neovim utilizes tree-sitter to render the inline OCaml within the returned markdown. However, the OCaml syntax is parsed as if it were a file, which causes tree-sitter parsing errors and results in poor highlighting. See screenshot:

<img width="519" alt="Screenshot 2024-02-27 at 11 46 22 AM" src="https://github.com/tree-sitter/tree-sitter-ocaml/assets/44309097/26904736-c27f-4c1f-bd2d-a9573620b571">

Alternatives considered:

1. Disable tree-sitter highlighting for hover in the Neovim client. Maybe it isn't right to use tree-sitter for this purpose.
2. Have the OCaml LSP server return slightly different OCaml code that _can_ be parsed correctly by tree-sitter.
3. Fork the OCaml tree-sitter grammar to create a different grammar that differs only in start symbol, namely a type expression.

I'd love to hear any thoughts!

**Comment by aryx** [comment]
I strongly +1 this one! It will be useful also for semgrep.

**Comment by 314eter** [comment]
@aryx Do you know how other languages do this?

I think there are two options:

1. Add this to the existing `source.ocaml.interface` grammar. I didn't try it yet, but I don't think there will be any conflicts. The downside is that a type is not an interface, so the name of the grammar wouldn't really be correct.
2. Create a new `source.ocaml.type` grammar with a different start symbol. That's very easy to do in this repository. The downside is that it will require some extra work and maintenance in projects that want to use it. In Neovim it would have to be added as a new grammar.

**Comment by mizlan** [comment]
In my limited exploration, other languages do not allow standalone type expressions. Rather, for situations like `textDocument/hover`, the syntax of their type expressions are generally not so exotic as to result in egregious parsing/highlighting. That is, their code returned from `textDocument/hover` looks similar enough to normal (term-level?) code that they get by, despite inspection revealing tree-sitter parse errors.

My 2 cents: I think adding it to `ocaml.interface` is not so heinous, and `ocaml.type` seems reasonable enough.

**Comment by aryx** [comment]
And no, I don't know other languages doing that, but I wish they do. Getting typehints is actually not even part of the LSP spec. ocamllsp abuse the textDocument/hover to provide those type hints. I wish it was part of the LSP spec because right now those textDocument/hover contain mixed info such as markdown and type which requires extra parsing ...
